[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["cd back/futureintern-backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd back/futureintern-backend && python init_db.py"]

[start]
cmd = "cd back/futureintern-backend && python run.py"
