[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["cd back/futureintern-backend && python init_db.py"]

[start]
cmd = "cd back/futureintern-backend && python run.py"
